version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    # use the Dockerfile next to this file
    build: .
    # sources environment variable configuration for our app
    # env_file: .env
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3001:3000"
    depends_on:
      - db
