default: &default
  adapter: postgresql
  pool: 25
  timeout: 5000

development:
  <<: *default
  database: readback_development

test:
  <<: *default
  database: readback_test

production:
  <<: *default
  database: readback_production
